# Generated by Django 3.2.12 on 2023-06-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230617_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='travail',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='fichiersens/'),
        ),
        migrations.AlterField(
            model_name='travail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
